name        'garethr-rustlang'
version     '0.0.1'
source      'git://github.com/garethr/garethr-rustlang.git'
author      'Gareth Rushgrove'
summary     'Module for installing rust from a ppa'
description 'Install rustlang packages'
license     'Apache License, Version 2.0'

dependency  'puppetlabs/apt', '>= 1.1.0'
dependency  'puppetlabs/stdlib', '>=3.2.0'
